export const ActionType = {
  ADD_TRIP: "Trips/ADD_TRIP",
  EDIT_TRIP: "Trips/EDIT_TRIP",
  DELETE_TRIP: "Trips/DELETE_TRIP",
  REMOVE_CLASS: "Trips/REMOVE_CLASS",
  LOADED_TRIPS: "Trips/LOADED_TRIPS",
  CHANGE_SORT_ORDER_TRIPS: "Trips/CHANGE_SORT_ORDER_TRIPS",
};