export const ActionType = {
  ADD_CUSTOMER: "Customers/ADD_CUSTOMER",
  EDIT_CUSTOMER: "Customers/EDIT_CUSTOMER",
  DELETE_CUSTOMER: "Customers/DELETE_CUSTOMER",
  LOADED_CUSTOMERS: "Customers/LOADED_CUSTOMERS",
  DELETE_CUSTOMERS_TRIPS_ID: "Customers/DELETE_CUSTOMERS_TRIPS_ID"
};