export const ActionType = {
  ADD_CUSTOMER: "Customers/ADD_CUSTOMER",
  EDIT_CUSTOMER: "Customers/EDIT_CUSTOMER",
  DELETE_CUSTOMER: "Customers/DELETE_CUSTOMER",
  LOADED_CUSTOMERS: "Customers/LOADED_CUSTOMERS",
  REMOVE_CLASS_CUSTOMER: "Customers/REMOVE_CLASS_CUSTOMER",
  CHANGE_SORT_ORDER_CUSTOMERS: "Customers/CHANGE_SORT_ORDER_CUSTOMERS",
};