export const ActionType = {
  LOADED_CUSTOMERS: "Customers/LOADED_CUSTOMERS",
  ADD_CUSTOMER: "Customers/ADD_CUSTOMER",
  EDIT_CUSTOMER: "Customers/EDIT_CUSTOMER",
  DELETE_CUSTOMER: "Customers/DELETE_CUSTOMER"
};