export const ActionType = {
  ADD_LOCATION: "Locations/ADD_LOCATION",
  EDIT_LOCATION: "Locations/EDIT_LOCATION",
  DELETE_LOCATION: "Locations/DELETE_LOCATION",
  LOADED_LOCATIONS: "Locations/LOADED_LOCATIONS",
  REMOVE_CLASS_LOCATION: "Locations/REMOVE_CLASS_LOCATION",
  CHANGE_SORT_ORDER_LOCATIONS: "Locations/CHANGE_SORT_ORDER_LOCATIONS",
};